import {parseTranscript,formatTime} from '../core/parser.js';
import {buildPlan} from '../core/planner.js';
import {DEFAULT_SETTINGS,DESIGN_PRESETS,getPreset} from '../core/designSystem.js';
import {drawMotion,preloadAssets} from '../core/motionRenderer.js';
import {renderVideo} from '../core/mediaRenderer.js';
const $=s=>document.querySelector(s); const $$=s=>[...document.querySelectorAll(s)]; const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
let file=null,url=null,cues=[],edits=[]; let settings={...DEFAULT_SETTINGS,testLength:15}; let renderBusy=false;
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(t._timer);t._timer=setTimeout(()=>t.classList.remove('show'),2400);}
function setState(text,kind='ok'){const x=$('#projectState');x.textContent=text;x.className='statePill'+(kind==='warn'?' warn':kind==='busy'?' busy':'');}
function progress(label,p,detail){$('#aiStatus').classList.remove('hide');$('#aiLabel').textContent=label;$('#aiPct').textContent=`${Math.round(p)}%`;$('#aiBar').value=Math.max(0,Math.min(1,p/100));$('#aiDetail').textContent=detail||'';}
function applySettings(){settings={...settings,design:$('#designSelect').value,vertical:$('#vertical').value,density:$('#density').value,motion:$('#motion').value,panelOpacity:Number($('#opacity').value),showTime:$('#showTime').checked,showLabel:$('#showLabel').checked,showLine:$('#showLine').checked,res:$('#qualityRes').value,fps:Number($('#fps').value),quality:$('#quality').value,testLength:Number($('#testLength').value)};edits.forEach((e,i)=>{e.position='right';e.vertical=settings.vertical});renderScene();}
function renderScene(){const v=$('#video'),stage=$('#stage'),canvas=$('#overlay');if(!file||stage.classList.contains('hide'))return;const r=stage.getBoundingClientRect(),d=Math.min(2,devicePixelRatio||1);canvas.width=Math.max(2,Math.floor(r.width*d));canvas.height=Math.max(2,Math.floor(r.height*d));const ctx=canvas.getContext('2d');ctx.setTransform(d,0,0,d,0,0);ctx.clearRect(0,0,r.width,r.height);edits.forEach(e=>drawMotion(ctx,e,v.currentTime||0,r.width,r.height,settings));$('#stageTime').textContent=formatTime(v.currentTime||0);}
function renderDesignCards(){const grid=$('#designGrid');grid.innerHTML=Object.values(DESIGN_PRESETS).map(p=>`<button class="designCard ${p.id===settings.design?'selected':''}" data-design="${p.id}"><div class="designMini"><span class="miniRule"></span><div class="miniCopy"><small>0:08</small><b>HÁ 4,6 BILHÕES</b><i>DE ANOS</i><em></em></div></div><strong>${p.name}</strong><small>${p.desc}</small></button>`).join('');$$('.designCard').forEach(b=>b.onclick=()=>{settings.design=b.dataset.design;$('#designSelect').value=settings.design;renderDesignCards();renderScene();});}
function renderCues(){const box=$('#transcriptPreview');box.innerHTML=cues.map((c,i)=>`<button class="cue ${edits.some(e=>Math.abs(e.start-c.start)<.12)?'hasMotion':''}" data-i="${i}"><time>${formatTime(c.start)} → ${formatTime(c.end)}</time><span>${esc(c.text)}</span><small>${edits.filter(e=>Math.abs(e.start-c.start)<.12).map(e=>esc(e.title)).join(' · ')||'sem visual automático'}</small></button>`).join('');$$('.cue').forEach(b=>b.onclick=()=>{$('#video').currentTime=cues[+b.dataset.i].start;renderScene();});}
function renderPlan(){const box=$('#autoList');if(!edits.length){box.innerHTML='<div class="empty big"><b>Nenhum motion selecionado</b><small>O motor só cria uma cena quando encontra uma informação visualmente explicável.</small></div>';return;}box.innerHTML=edits.map((e,i)=>`<article class="autoItem ${e.enabled===false?'off':''}"><button class="autoToggle" data-i="${i}">${e.enabled===false?'○':'✓'}</button><div><b>${esc(e.title)}</b><strong>${esc(e.data||e.title)}</strong><small>${formatTime(e.start)} · ${esc(e.subtitle||e.source)}</small></div></article>`).join('');$$('.autoToggle').forEach(b=>b.onclick=()=>{edits[+b.dataset.i].enabled=edits[+b.dataset.i].enabled===false;renderPlan();renderScene();});}
function analyze(){if(!file){toast('Importe o vídeo primeiro.');return;}if(!cues.length){toast('Insira a transcrição marcada.');return;}setState('ANALISANDO · PLANEJAMENTO','busy');progress('Interpretando timestamps',30,`${cues.length} trechos recebidos`);setTimeout(()=>{edits=buildPlan(cues);edits.forEach(e=>{e.vertical=settings.vertical;e.design=settings.design;});progress('Construindo direção de arte',72,`${edits.length} cenas automáticas`);renderPlan();renderCues();renderScene();setTimeout(()=>{progress('Projeto pronto',100,'Sem Whisper · sem efeitos sonoros · áudio original preservado');setState('PRONTO · RENDER LOCAL');$('#test').disabled=!edits.length;$('#render').disabled=false;toast(`${edits.length} cenas criadas`);},180);},180);}
function setVideo(f){if(!f)return;file=f;if(url)URL.revokeObjectURL(url);url=URL.createObjectURL(f);const v=$('#video');v.src=url;v.onloadedmetadata=()=>{$('#fileInfo').innerHTML=`<b>${esc(f.name)}</b><span>${v.videoWidth}×${v.videoHeight} · ${formatTime(v.duration)}</span>`;$('#fileInfo').classList.remove('hide');$('#stageWrap').classList.remove('hide');$('#controls').classList.remove('hide');$('#seek').max=v.duration||1;$('#analyzeBtn').disabled=!cues.length;$('#render').disabled=false;renderScene();};$('#mediaBadge').textContent='VÍDEO CARREGADO';toast('Vídeo carregado');}
function setTranscript(text,name='paste.txt'){try{cues=parseTranscript(text,name,Number($('#video').duration)||0);$('#transcriptBadge').textContent=`${cues.length} TRECHOS`;$('#transcriptPreview').innerHTML='';$('#analyzeBtn').disabled=!file;toast(`${cues.length} trechos reconhecidos`);renderCues();if(file)analyze();}catch(err){toast(err.message||'Falha ao ler a transcrição.');}}
$('#file').onchange=e=>setVideo(e.target.files?.[0]);$('#drop').onclick=e=>{if(e.target.id!=='file')$('#file').click();};$('#drop').ondragover=e=>e.preventDefault();$('#drop').ondrop=e=>{e.preventDefault();setVideo(e.dataTransfer.files?.[0]);};
$('#transcriptFile').onchange=async e=>{const f=e.target.files?.[0];if(f)setTranscript(await f.text(),f.name);};$('#parsePaste').onclick=()=>setTranscript($('#transcriptInput').value);
$('#analyzeBtn').onclick=analyze;
['designSelect','vertical','density','motion','opacity','qualityRes','fps','quality','testLength'].forEach(id=>$(id).addEventListener('input',applySettings));['showTime','showLabel','showLine'].forEach(id=>$(id).addEventListener('change',applySettings));
$('#video').ontimeupdate=()=>{$('#seek').value=$('#video').currentTime||0;$('#clock').textContent=`${formatTime($('#video').currentTime)} / ${formatTime($('#video').duration)}`;renderScene();};$('#seek').oninput=()=>{$('#video').currentTime=Number($('#seek').value);renderScene();};$('#play').onclick=()=>{const v=$('#video');if(v.paused){v.play();$('#play').textContent='❚❚';}else{v.pause();$('#play').textContent='▶';}};
$('#test').onclick=()=>doRender(true);$('#render').onclick=()=>doRender(false);$('#help').onclick=()=>$('#modal').classList.remove('hide');$('#close').onclick=()=>$('#modal').classList.add('hide');window.addEventListener('resize',renderScene);
async function doRender(test){if(renderBusy||!file||!edits.length){toast('Prepare o vídeo e gere as cenas.');return;}renderBusy=true;$('#render').disabled=true;$('#test').disabled=true;$('#progress').classList.remove('hide');$('#bar').value=0;$('#ppct').textContent='0%';setState('RENDERIZANDO · LOCAL','busy');try{const blob=await renderVideo({file,videoElement:$('#video'),edits,settings,test,onProgress:p=>{$('#bar').value=p;$('#ppct').textContent=`${Math.round(p*100)}%`;}});const href=URL.createObjectURL(blob);$('#result').classList.remove('hide');$('#result').innerHTML=`<div class="success"><div><b>✓ MP4 concluído</b><small>Vídeo + áudio original · sem SFX</small></div><a href="${href}" download="AutoMotion_Documentary_${test?'teste':'final'}.mp4">Salvar MP4</a></div>`;setState('PRONTO · EXPORTADO');toast('Render concluído.');}catch(err){console.error(err);setState('ERRO · REVISAR','warn');toast(`Falha no render: ${err.message||'erro desconhecido'}`);}finally{renderBusy=false;$('#render').disabled=false;$('#test').disabled=!edits.length;}}
renderDesignCards();applySettings();preloadAssets('./assets/').catch(()=>{});renderPlan();
